---
# wait for key
- name: wait for public key creation
  ansible.builtin.wait_for:
    path: "{{ gitlab_ce_persistent_path }}/config/initial_root_password"
    state: present

# initial_root_password
- name: read initial_root_password
  ansible.builtin.slurp:
    src: "{{ gitlab_ce_persistent_path }}/config/initial_root_password"
  register: gitlab_ce_initial_root_password

# display public key
- name: display public key
  ansible.builtin.debug:
    msg: "The gitlab-ce initial root password is: {{ gitlab_ce_initial_root_password['content'] | b64decode }}. If not allready done: please change this immediately. "
...