---
- name: Check if certificate exist
  ansible.builtin.stat:
    path: "{{ ssl_crt_path }}"
  register: ssl_crt_path_result

- name: Configure gitlab for acme ssl
  block:
    # create gitlab service (restart or stop container)
    - name: Configue systemd service for gitlab
      block:
        - name: Copy gitlab.service to systemd configs
          ansible.builtin.template:
            src: gitlab.service.j2
            dest: /etc/systemd/system/gitlab.service
            owner: root
            group: root
            mode: '0644'

        - name: Enable service gitlab.service and ensure it is not masked
          ansible.builtin.systemd:
            name: gitlab
            state: started
            enabled: true
            masked: false
            daemon_reload: true

      # certificates
      # service to create or renew certificates
    - name: Configure gitlab SSL acme environment
      block:
          # Bash script to regenerate certificates new or renew
        - name: Copy gitlab-regenerate-certificate.sh.j2
          ansible.builtin.template:
            src: gitlab-regenerate-certificate.sh.j2
            dest: '/usr/local/bin/gitlab-regenerate-certificate.sh'
            owner: root
            group: root
            mode: '0770'

        - name: Copy gitlab-regenerate-certificate.service to systemd configs
          ansible.builtin.copy:
            src: gitlab-regenerate-certificate.service
            dest: /etc/systemd/system/gitlab-regenerate-certificate.service
            owner: root
            group: root
            mode: '0644'

        - name: Enable service gitlab-regenerate-certificate and ensure it is not masked
          ansible.builtin.systemd:
            name: gitlab-regenerate-certificate
            state: started
            enabled: true
            masked: false
            daemon_reload: true

        # copy service to trigger the gitlab.service for restart, because cert has changed
        - name: Copy gitlab-ssl.service to systemd configs
          ansible.builtin.copy:
            src: gitlab-ssl.service
            dest: /etc/systemd/system/gitlab-ssl.service
            owner: root
            group: root
            mode: '0644'

        # whatchdog for the cert path
        - name: Copy gitlab-ssl.path
          ansible.builtin.template:
            src: gitlab-ssl.path.j2
            dest: '/etc/systemd/system/gitlab-ssl.path'
            owner: root
            group: root
            mode: '0644'

        - name: Make sure gitlab-ssl.path service unit is running
          ansible.builtin.systemd:
            name: gitlab-ssl.path
            state: started
            enabled: true
            masked: false
            daemon_reload: true
  when: ssl_crt_path is defined and ssl_crt_path_result.stat.exists
...
